services:

  db:
    container_name: postgres
    image: postgres
    volumes:
      - cardapioDB:/var/lib/postgresql/data/pgdata
    env_file:
      - env-dev
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5433
    ports:
      - '5433:5433'
volumes:
  cardapioDB:
    external: true
