services:
  spring-app:
    container_name: spring-app
    build:
      context: . # O diretório onde está o seu Dockerfile
      dockerfile: Dockerfile # Nome do seu Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db # Garanta que o contêiner do banco de dados esteja em execução antes de iniciar o aplicativo Spring Boot

  db:
    container_name: postgres
    image: postgres
    volumes:
      - cardapioDB:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5433
    ports:
      - '5433:5433'
volumes:
  cardapioDB:
    external: true
